name: CI
on: [push, repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        duckdb_version: ['<submodule_version>']
    env:
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      VCPKG_TARGET_TRIPLET: 'x64-linux'
      GEN: ninja
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install Ninja
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build cmake build-essential

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != '<submodule_version>' }}
        run: cd duckdb && git checkout ${{ matrix.duckdb_version }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Build
        run: make

      - name: Test
        run: make test

  macos:
    name: MacOS
    runs-on: macos-latest 
    strategy:
      matrix:
        duckdb_version: ['<submodule_version>']
    env:
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      VCPKG_TARGET_TRIPLET: 'x64-osx'
      OSX_BUILD_ARCH: 'x86_64'
      GEN: ninja
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install Ninja
        run: brew install ninja

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != '<submodule_version>' }}
        run: cd duckdb && git checkout ${{ matrix.duckdb_version }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Build
        run: make

      - name: Test
        run: make test

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        duckdb_version: ['<submodule_version>']
    env:
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      VCPKG_TARGET_TRIPLET: 'x64-windows-static-md'
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != '<submodule_version>' }}
        run: cd duckdb && git checkout ${{ matrix.duckdb_version }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Build
        run: make

      - name: Test
        run: build/release/test/Release/unittest.exe
